############################################
# GitHub Actions workflow template 2
############################################

name: GitHub Actions Workflow Template 2

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      input1:
        required: true
        type: string
      input2:
        required: true
        type: string
      input_env1:
        required: true
        type: string
      input_env2:
        required: true
        type: string
      runs-on:
        default: 'ubuntu-latest'
        required: false
        type: string

jobs:
  template2:
    name: Template 2 (${{ inputs.environment }})
    environment: '${{ inputs.environment }}'
    runs-on: '${{ inputs.runs-on }}'
    steps:
      - name: Goodbye world (${{ inputs.environment }})
        run: |
          echo "Goodbye world"
      - name: Display inputs (${{ inputs.environment }})
        run: |
          echo "Input 1: ${{ inputs.input1 }}"
          echo "Input 2: ${{ inputs.input2 }}"
          echo "Input ENV 1: ${{ inputs.input_env1 }}"
          echo "Input ENV 2: ${{ inputs.input_env2 }}"
